name: CI Master

on:
  push:
    branches: [ "master" ]

jobs:
  format-checker:
    name: Format Checker
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'
      - name: Check Formatting
        run: ./gradlew ktlintCheck

  build:
    name: Build and Analyze
    runs-on: ubuntu-slim
    needs: format-checker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'gradle'
    - name: Build and analyze
      run: ./gradlew build sonar --info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v6
      if: success() || failure() # always run even if the previous step fails
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: '**/test/TEST-*.xml'
        require_tests: true
        annotate_notice: false
